In [24]:
import numpy as np
import importlib
import ase
mp = importlib.import_module("molpy")
# from molpy.base import Node
Atom = mp.Atom
Group = mp.Group
mp.System

molpy.system.System

In [25]:
# define atoms in H2O
H1 = Atom('H1')
H2 = Atom('H2')
O  = Atom('O')

# define topology connection
O.bondto(H1)
O.bondto(H2)

# define molecule
H2O = Group('H2O')

# add atoms to the molecule
H2O.addAtoms([H1, H2, O])
H2O.addBond(O, H1)
H2O.addBond(O, H2)

O.element = "O"
print(O.element)
O.setElement("UNK")
O.Element = "UNK1"
print(O.Element)

UNK1


In [26]:
CC_bond = 1.42
GRA = ase.build.graphene_nanoribbon(10, 10, vacuum = CC_bond/2)
GRA.cell[1] = [0, 20, 0]
GRA.positions[:,1] = 10
GRA.pbc = [True, True, True]
ase.io.write("GRA.cif", GRA)
GRA_sys = mp.fromASE_S(GRA)

In [27]:
mp.build_neigh(GRA_sys)
mp.auto_bonds(GRA_sys)

< System C200 >


In [28]:
Ni = ase.io.read("./tests/samples/Ni.cif")

In [29]:
ase_cell = Ni.cell

In [30]:
ase_cell

Cell([[2.757716, 0.0, 0.0], [1.3788581667314475, 2.388252016160353, 0.0], [1.3788581667314475, 0.7960840695617433, 2.2516655717232976]])

In [31]:
angles = ase_cell.angles()
lengths = ase_cell.lengths()

In [32]:
lbox = lengths[0]
box = mp.Box("ppp", lx = lbox, ly = lbox, lz = lbox, alpha = angles[0], beta = angles[1], gamma = angles[2])

In [33]:
box.angles()

array([59.999996, 59.999996, 59.999996])

In [34]:
cell_v = box._cellpar.T

In [35]:
box = mp.Box("ppp", a1 = cell_v[0], a2 = cell_v[1], a3 = cell_v[2],)

d:\Project\molpy\molpy\box.py:83: RuntimeWarning: divide by zero encountered in true_divide
  self.xz = a3x/self.lz
d:\Project\molpy\molpy\box.py:84: RuntimeWarning: divide by zero encountered in true_divide
  self.yz = (a2@a3-a2x*a3x)/self.ly/self.lz
d:\Project\molpy\molpy\box.py:127: RuntimeWarning: invalid value encountered in multiply
  [self.lx, self.xy*self.ly, self.xz*self.lz],
d:\Project\molpy\molpy\box.py:128: RuntimeWarning: invalid value encountered in multiply
  [0, self.ly, self.yz*self.lz],
d:\Project\molpy\molpy\box.py:126: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self._cellpar = np.array([


In [36]:
ase_cell.volume

14.829741449810445

In [37]:
box._cellpar

array([[2.757716, 1.1941261524738398,
        array([       nan,        nan, 1.12583292])],
       [0, 2.388252016160353,
        array([       nan,        nan, 0.64999989])],
       [0, 0, array([0.        , 0.        , 2.25166557])]], dtype=object)

In [38]:
ase_cell.volume

14.829741449810445