In [1]:
import numpy as np
import importlib
import ase
mp = importlib.import_module("molpy")
# from molpy.base import Node
Atom = mp.Atom
Group = mp.Group
mp.System

molpy.system.System

In [2]:
# define atoms in H2O
H1 = Atom('H1')
H2 = Atom('H2')
O  = Atom('O')

# define topology connection
O.bondto(H1)
O.bondto(H2)

# define molecule
H2O = Group('H2O')

# add atoms to the molecule
H2O.addAtoms([H1, H2, O])
H2O.addBond(O, H1)
H2O.addBond(O, H2)

< Bond O-H2 >

In [3]:
O.element = "O"

In [4]:
print(O.element)
O.setElement("UNK")
O.Element = "UNK1"
print(O.Element)


UNK1


In [5]:
class B(object):
    __slots__ = ('_fields')
    def __init__(self):
        self._fields = set()

    @property
    def fields(self):
        return self._fields



In [6]:
ase.io.read("UiO-66_vesta.cif")
from ase.io.cif import parse_cif

In [7]:
CIF_block = ase.io.cif.parse_cif("UiO-66_vesta.cif")

In [8]:
cif = next(CIF_block)

In [9]:
atomNames = cif.get("_atom_site_label")

In [10]:
cif.get_unsymmetrized_structure()

Atoms(symbols='ZrO2HC3H', pbc=False, cell=[20.7439, 20.7439, 20.7439])

In [11]:
spacegroup = cif.get_spacegroup(True)

In [12]:
xyz = cif.get_unsymmetrized_structure()
xyz.get_scaled_positions()

array([[ 0.11961 ,  0.      ,  0.      ],
       [ 0.17335 , -0.0923  ,  0.      ],
       [ 0.0679  ,  0.0679  ,  0.0679  ],
       [ 0.0901  ,  0.0901  ,  0.0901  ],
       [ 0.1516  , -0.1516  ,  0.      ],
       [ 0.2028  , -0.2028  ,  0.      ],
       [ 0.2671  , -0.1855  ,  0.      ],
       [ 0.278904, -0.1413  ,  0.      ]])

In [13]:
_, kinds = spacegroup.equivalent_sites([0.1, 0, 0])

In [14]:
g = mp.fromCIF("UiO-66_vesta.cif")

In [15]:
CC_bond = 1.42
GRA = ase.build.graphene_nanoribbon(10, 10, vacuum = CC_bond/2)
GRA.cell[1] = [0, 20, 0]
GRA.positions[:,1] = 10
GRA.pbc = [True, True, True]
ase.io.write("GRA.cif", GRA)
GRA_sys = mp.fromASE_S(GRA)

In [16]:
n = ase.neighborlist.build_neighbor_list(GRA, cutoffs = [5] * len(GRA), self_interaction=False, bothways=True)

In [17]:
x, y, z = ase.neighborlist.neighbor_list("ijd", GRA, cutoff = 2.4, self_interaction=False)

In [18]:
GRA_sys.cutoff()

1.62

In [19]:
mp.build_neigh(GRA_sys)

< System C200 >


In [20]:
x = GRA_sys._neigh_csc[2]
x.data

array([1.42, 1.42, 1.42])

In [21]:
y = x.tocoo()

In [22]:
import scipy.sparse 
scipy.sparse.find(x)

(array([0, 0, 0]), array([  1,   3, 181]), array([1.42, 1.42, 1.42]))

In [23]:
mp.auto_bonds(GRA_sys)

add 1.42 0.9
add 1.4199999999999997 0.9
add 1.4200000000000017 0.9
add 1.42 0.9
add 1.42 0.9
add 1.42 0.9
add 1.42 0.9
add 1.4200000000000002 0.9
add 1.4200000000000017 0.9
add 1.4200000000000002 0.9
add 1.4199999999999997 0.9
add 1.42 0.9
add 1.4199999999999997 0.9
add 1.4199999999999997 0.9
add 1.4200000000000017 0.9
add 1.4199999999999997 0.9
add 1.4200000000000006 0.9
add 1.42 0.9
add 1.4200000000000006 0.9
add 1.4199999999999997 0.9
add 1.4200000000000017 0.9
add 1.4199999999999997 0.9
add 1.4199999999999997 0.9
add 1.42 0.9
add 1.4199999999999997 0.9
add 1.4199999999999997 0.9
add 1.4200000000000017 0.9
add 1.4199999999999997 0.9
add 1.4199999999999997 0.9
add 1.42 0.9
add 1.4199999999999997 0.9
add 1.4199999999999997 0.9
add 1.4200000000000017 0.9
add 1.4199999999999997 0.9
add 1.4200000000000013 0.9
add 1.42 0.9
add 1.4200000000000013 0.9
add 1.4199999999999997 0.9
add 1.4200000000000017 0.9
add 1.4199999999999997 0.9
add 1.4199999999999997 0.9
add 1.42 0.9
add 1.41999999999999

KeyError: 'typeID not in < Bond C-C > and its bondType'

< System C200 >